global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Http.Features;
global using Microsoft.AspNetCore.Mvc;
global using SitRep.Abstractions;
global using SitRep.Ticketing;
global using SitRep.Ticketing.Transitions;
global using SitRepExamples.Api.Endpoints;
global using SitRepExamples.Api.Endpoints.CoreApi;
global using SitRepExamples.Api.Endpoints.CoreApi.Models;
global using SitRepExamples.Api.Endpoints.SanityChecks;
global using System.Net;
global using System.Text.Json.Serialization;
global using JsonOptions = Microsoft.AspNetCore.Http.Json.JsonOptions;
